---
- name: System Initialization
  hosts: "{{ host | default('localhost') }}"
  become: true
  gather_facts: true
  vars:
    upgrade: false
    sysinit_var: system_initialization
    install_sysinit: true
    install_reach: true
  roles:
    - role: sysinit
      when: install_sysinit | bool
    - role: reach
      when: install_reach | bool
