---
- name: Configure sudo access
  ansible.builtin.include_tasks: "sudoers.yml"

- name: Configure host
  ansible.builtin.include_tasks: "host.yml"

- name: Configure SELinux
  ansible.builtin.include_tasks: "selinux.yml"

- name: Configure user preferences
  ansible.builtin.include_tasks: "user.yml"

- name: Configure SSH
  ansible.builtin.import_tasks: "ssh.yml"
  tags:
    - repos

- name: Install repositories
  ansible.builtin.import_tasks: "repos.yml"
  tags:
    - repos
