---
sysinit_debug: false
sysinit_force_update: false

sysinit_packages:
  - gcc
  - make
  - rsync
  - unzip
  - xclip
  - xsel
  - zip

sysinit_sys_tools:
  - mise

sysinit_mise_plugins:
  - amazon-ecr-credential-helper
  - awscli
  - github-cli
  - granted
  - jq
  - mkcert
  - node
  - pre-commit
  - python@3.11
  - starship
  - usage
