#!/bin/bash

# Connect to an instance via SSM
aws-ssm_connect() {
  dbconnect=false

  if [[ "$1" =~ "-h" ]] || [[ "$1" = "--help" ]]; then
    cat <<EOF
Connect to an instance via SSM
Usage:
  aws-ssm_connect [-db | <intance-name|instance-id> ] [ <host>:rch-cf-rds-engine ] [ <port>:5432 ] [ <local_port>:\$port ] }

Connect Examples:
  aws-ssm_connect               : search for an instance to connect to
  aws-ssm_connect instance-name : connect to an instance named instance-name
  aws-ssm_connect i-XXXXXXXXXX  : connect to an instance by instance-id

Port Forwarding Examples:
  aws-ssm_connect -db : db forwarding - forwarding  port 5432 to remote port 5432, engine database
  aws-ssm_connect my-instance rch-cf-rds-engine.rch 5432 9999 : forwarding local port 9999 to remote port 5432"
EOF
  elif [ -n "$AWS_PROFILE" ]; then
    if [ "$1" = "-db" ]; then
      shift
      dbconnect=true
    fi

    local instanceIdentifier=$1
    local instanceId=""

    if [[ "${instanceIdentifier:0:2}" == "i-" ]]; then
      instanceId=$instanceIdentifier
    else
      [ "$dbconnect" = "true" ] && instanceIdentifier="CheckoutEngine"

      aws-get_all_running_instances "${instanceIdentifier}"

      if [ -z "$instance_array" ]; then
        echo "No running instances found"
        return
      elif [ "{{ '{#' }}instance_array[@]}" -eq 1 ]; then
        instanceId=$(echo "${instance_array[0]}" | sed 's/\"//g' | cut -d' ' -f2)
      else
        PS3='Select instance to connect to, or 0 to exit: '
        select instanceIdentifier in "${instance_array[@]}"; do
          if [[ $REPLY == "0" ]]; then
            return
          elif [[ -z $instanceIdentifier ]]; then
            printf '"%s" is not a valid choice\n' "$REPLY" >&2
          else
            break
          fi
        done
        instanceId=$(echo "${instanceIdentifier}" | sed 's/\"//g' | cut -d' ' -f2)
      fi
    fi

    if [[ "${dbconnect}" = "true" ]]; then
      echo ""
      dbs=("engine" "index" "timeline")
      PS3='Select db to connect to, or 0 to exit: '
      select db in "${dbs[@]}"; do
        if [[ $REPLY == "0" ]]; then
          return
        elif [[ -z "$db" ]]; then
          printf '"%s" is not a valid choice\n' "$REPLY" >&2
        else
          break
        fi
      done

      local host="rch-cf-rds-$db"
      local port=5432
      local local_port=$port

      aws ssm start-session --target "$instanceId" \
        --document-name AWS-StartPortForwardingSessionToRemoteHost \
        --parameters "{\"host\":[\"$host\"],\"portNumber\":[\"$port\"], \"localPortNumber\":[\"$local_port\"]}"
    else
      aws ssm start-session --target "$instanceId"
    fi
  else
    echo 'No profile is set'
    return 1
  fi
}

# Queries AWS SSM for a list of running instances
aws-get_all_running_instances() {
  local instance_name="$1"
  local query_search

  if [[ -n "$instance_name" ]]; then
    query_search=" && Tags[?Key=='Name' && contains(Value, '$instance_name')]].[Tags[?Key=='Name']"
  else
    query_search="].[Tags[?Key=='Name']"
  fi

  local query="Reservations[].Instances[?State.Name == 'running'${query_search} | [0].Value, InstanceId][]"
  
  case "$(uname -s)" in
    Linux*)
      if [[ -n "$BASH_VERSION" ]]; then
        readarray -t instance_array < <(aws ec2 describe-instances --query "$query" --output json | jq -r 'sort_by(.[]) | .[] | join(" ")')
      elif [[ -n "$ZSH_VERSION" ]]; then
        instance_array=("${(@f)$(aws ec2 describe-instances --query "$query" --output json | jq -r 'sort_by(.[]) | .[] | join(" ")')}")
      fi
      ;;
    Darwin*) # macOS
      instance_array=("${(@f)$(aws ec2 describe-instances --query "$query" --output json | jq -r 'sort_by(.[]) | .[] | join(" ")')}")
      ;;
  esac
}

# Get instance ID(s)
aws-get_instance() {
  if [[ -n "$BASH_VERSION" ]]; then
    readarray -t instanceArray <<< "$1"
  elif [[ -n "$ZSH_VERSION" ]]; then
    instanceArray=("${(@f)$1}")
  fi

  local instances=""
  for instanceIdentifier in "${instanceArray[@]}"; do
    if [[ "${instanceIdentifier:0:2}" == "i-" ]]; then
      instance_id=$(aws ec2 describe-instances --instance-ids "$instanceIdentifier" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[]" --output text)
    else
      instance_id=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=$instanceIdentifier" --query "Reservations[].Instances[?State.Name == 'running'].InstanceId[]" --output text)
    fi
    instances+="$instance_id "
  done

  instances=$(echo "$instances" | xargs)  # Trim excess whitespace
  echo "$instances"
}

# Get AWS VPN Client Endpoint
aws-get_vpn_client_endpoint() {
  local profile=${1:-$AWS_PROFILE}
  local region=${2:-$AWS_REGION}

  if [[ "$1" == "-h" || "$1" == "--help" || -z "$profile" ]]; then
    cat <<EOF
Usage: aws-get_vpn_client_endpoint [<profile>] [<region>]
Get client VPN endpoint configuration.
Use arguments to provide profile/region or use the logged-in profile/region.
Parameters:
  profile:  AWS profile
  region:   AWS region
EOF
    return 1
  else
    if [[ "$profile" == "$AWS_PROFILE" ]]; then
      aws ec2 export-client-vpn-client-configuration \
        --client-vpn-endpoint-id "$(aws ec2 describe-client-vpn-endpoints \
          --query "ClientVpnEndpoints[0].ClientVpnEndpointId" --output text)" \
        --output text | tee "${profile}_client_vpn.ovpn"
    else
      aws-profile_switcher "$profile" -r "$region" --exec -- "aws ec2 export-client-vpn-client-configuration \
        --client-vpn-endpoint-id $(aws-profile_switcher "$profile" -r "$region" --exec -- aws ec2 describe-client-vpn-endpoints \
        --query 'ClientVpnEndpoints[0].ClientVpnEndpointId' --output text) \
        --output text | tee \"${profile}_client_vpn.ovpn\""
    fi

    # Remove 'verify-x509-name' line from .ovpn file
    if [[ -n "$BASH_VERSION" ]]; then
      sed -i '/verify-x509-name/d' "${profile}_client_vpn.ovpn"
    elif [[ -n "$ZSH_VERSION" ]]; then
      sed -i '' '/verify-x509-name/d' "${profile}_client_vpn.ovpn"
    fi
  fi
  return 0
}

alias c='aws-ssm_connect'